name: vcmrtd
description: Veriable Credentials from Machine Readable Travel Documents

version: 2.0.0
publish_to: none

environment:
  sdk: ^3.8.0

dependency_overrides:
  pointycastle:
    git:
      url: https://github.com/privacybydesign/pc-dart.git
      ref: master

dependencies:
  flutter:
    sdk: flutter
  archive: ^4.0.2
  collection: ^1.19.0
  convert: ^3.1.2
  crypto: ^3.0.6
  expandable: ^5.0.1
  http: ^1.5.0
  fixnum: ^1.1.1
  flutter_nfc_kit:
    git:
      url: https://github.com/privacybydesign/flutter_nfc_kit.git
      ref: bb6fb63c857cb223f7f58f4e2a78165a4f0b07ab
  intl: ^0.20.2
  json_annotation: ^4.9.0
  logging: ^1.3.0
  meta: ^1.15.0
  tripledes_nullsafety: ^1.0.3
  flutter_riverpod: ^2.6.1
  pointycastle:
    git:
      url: https://github.com/privacybydesign/pc-dart.git
      ref: master
  diffie_hellman: ^0.1.2
  logger: ^2.3.0

dev_dependencies:
  json_serializable: ^6.6.1
  build_runner: ^2.5.4
  flutter_lints: ^6.0.0
  flutter_test: # needed for flutter_nfc_kit
    sdk: flutter
  test: ^1.16.5
  lints: ^6.0.0
